language: generic
sudo: required
services:
- docker
before_install:
- set -e
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp
    rm -rf /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
  fi
install: scripts/travis-setup.sh
jobs:
  include:
  - stage: Linux+macOS
    if: "(type = push) AND ((branch IN (master, bulk)) OR (fork = true))"
    os: linux
    script: scripts/travis-run.sh
  - os: osx
    if: "(type = push) AND ((branch IN (master, bulk)) OR (fork = true))"
    script: scripts/travis-run.sh
  - stage: Linux
    if: type = pull_request
    os: linux
    script: scripts/travis-run.sh
env:
  global:
  - SUBDAGS=1
  - BIOCONDA_UTILS_TAG=master
  - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
  - BIOCONDA_UTILS_LINT_ARGS=
  - MINICONDA_VER="4.3.21"
  - ANACONDA_USER='nyuad-cgsb'
  - GITHUB_USER='nyuad-cgsb'
  - MY_TRAVIS_REPO_SLUG='biosails/bioconda-recipes'
  matrix:
  - SUBDAG=0
matrix:
  fast_finish: true
