language: generic
sudo: required
services:
- docker
before_install:
- set -e
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp
    rm -rf /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
  fi
install: scripts/travis-setup.sh
jobs:
  include:
  - stage: Linux+macOS
    if: "(type = push) AND ((branch IN (master, bulk)) OR (fork = true))"
    os: linux
    script: scripts/travis-run.sh
  - stage: Linux
    if: type = pull_request
    os: linux
    script: scripts/travis-run.sh
env:
  global:
  - SUBDAGS=1
  - BIOCONDA_UTILS_TAG=master
  - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
  - BIOCONDA_UTILS_LINT_ARGS=
  - MINICONDA_VER="4.3.21"
  - ANACONDA_USER='nyuad-cgsb'
  - GITHUB_USER='nyuad-cgsb'
  - MY_TRAVIS_REPO_SLUG='biosails/bioconda-recipes'
  - CONTAINER_NAMESPACE='nyuad_cgsb'
  - secure: TAqRfTEXtxTFDD47ItuW3uOicKVi2vPUXdKT1C6/oh0lYycOUQYf3cXYGt05LasxmxfOfRzOOpcYQUZ0vynt7zl0XjD+d77FQm4xfVCyYxJRwcCrZbhvFAwSAUQ4g49NsoUpyffNOYLVpHWYgF8HHvi8Hx7KMqypHuxzwrH4b9r2VVMdkcON1iOUdwl0CZzNAytvoC+K/HWywXEBhG44Y5dO04fOMXYzm9LmlLM4w4Z00x2IlbXES7vg5m7uzN3k4ATUCNxlW90HxzuAnqopaT3CpntVlSxkbpineMNUefztyJcfuVYuMlAVsMDNP6GlU6I+UyypDNRf7IsWkECOI7RnQPKyg6XI7K3IORk/eHwEPYyz1TWGV3KTMxIR9DW0qD6fVIWO5JdLUpknPGGNp7uKgSkP6D+ejoQsbBqurU0l/0TnfN+okB4uk5wxiosSD0js/CBhnpQiasdKfORmGBbmCW7KsMryIRrTQJcP02ZHv/sfYHtl8HYZWyvSYcApL+zHisJZ8GjyFWUqqcoYfG7tKJXQsltGuaC8d4XYgppiEfxDE+RuOvwFCHXYgL577QZdr5p8VKTHIn+QrSI++Zp/5CG4LXg6V4hroz37CCQVlC6sk2Q/7YLeJ3afWkPfMqB/MUVzGo2QxICroaET+wleiH5ODPr2qxxsFPmhcyc=
  - secure: h2M/Xsl++EqD+6C1wc7JqOTTLtOYOOoO4OodBLZGZ5wDwNOk6hsrSQJ3YPPP72U9d1KcYss1c/wFp9qsBtoVaMK7lCUQQ1UFt4upo2ilgw4vvh6Z9GAXCuoqNGGlI4fI+/g15buAfi1ztGTYB1shCT7IrJVL5Xop0aP1OpXwIstdQVxNIRNAMrUSwUEF4Czd/neZOsw/y0bu8OlT+RZm3rN64ajKPTDzXhyUQTpdLi4fJrjXE1RyNKhF+y4Rt3EN7IucPUJoIS18nw6lKLFvo99YGIKzGeRD+sQDutfbpJAyp7vi19hhTarDlGzx8nAWpEbZsi6Mx07lU3HcXobR8gkkHeAS8/W2AmsdO0Wr+YxyHTYxxlvVECrnIQ+0UKbHHed01+krDAsATQUgaJoEimM5Kn/OKmAfLDLyzI486Q8Pr+fjK6mxhrzNHo2ut5dnIvJZfgTTxxH0u5W/kMsfh5zyGb5vPHGebKf9WWcf0AvyU9IHckLjw3l6VVbdXSv8Gd0UqdGWv1eFpqjlD1OykVzclOVp+W+940nC+N6AyvnH45DjbcgLY5/thK7FjFw/HHJj4ilM0CdF1cBST9bv40hJhtkFI8tOhs/w/reyHwb0Qypp2aC/wSjILZgychnQR78LNqHFPuqsFF5A7ZTRvUsKaAZ3kZkbV3deEMgXlQk=
  - secure: ZP24WsYmw8BPFK42HZLmu+L4yQGwMlQxh8dspUqhBYAFCia1u6/NGIHXSPprViSmWYoNn5Yn/rO/tI8tCT8UaARFAwq5hz6kTzmZ+4Hf0cSLaUCtQ0KsRSxzAuwRlL4oaIWs5M0JH2WpAbPCjXdmfNbHn/LEz2lYnOnYNGHuG0E2XIVgrLnGRkiEyx4BO68b8+3DdP0V+pQ9vos4grsrXOaPQbTSFKXHqmQ3NBxPpQCft0FDfBD/3lF8C15RwT0Wg22pj3FZ62pWR7V0AUPgpcbt4GPV1YsZbdl2P90putJY761QqtiWQN32QSNTS022OsH0d/3Z/r4MO0u6yPNNI+ZC8aSbzoLZHjOHHPNMVMMDjS3ZGvlLJh//kxM7Q+mVBT9JK0wf1YAFZW1tZDXN1mC5Y7yCdjh0L2Ix0BPx89NdeRLoya+fMOPfZt/iUR/ugaAI9m2OYuUdAMukFuOCeIk7ykXyQ5xnlJTk3pd/awbqdY/ejhglzBwVu/9vovvRUbC00sSL6W6warBNHpRIRNJpiOvvLZNFgZlnp3iQF7+5Kq0WiMmhSpEZnyIdPmV3s5IpRa9kBa3vcRBtMqLhpa5WNgxYaCZC1mwsPdXghfWwSzGdpTG22n5FdQaM9wMt8WsahLqXfPpRPHckOfYQzmsyWYDivB4271rN8qWNRXI=
  - secure: H/Bt8NnFPbt1PTpQF7VZTuMvH9GohUUIlf6+xLo8IkaQe3o9jEmB5bEMFQfIkCnWLN9PvcWrGArVCFTGco9OItIXPFitLs5zmBDQyNGWwpE9iKiRXgjT886OYWVAHWFLso/72OC+vQPrGoz9D+X/nTYhlUZPOqoMVGtDggpTHu3tkCH0v9yRWXOwHWeJrJQ7F3kwcHXxqW+2Xiz38b3JUp8tDFvv3QLO4IKMv3BoybWp1UDJ6XbthDx2X5oA1sCgoOOmm9mCsnCc7QijYoo/S1yNQ9YURYQvFCt+QHCf5JEVN4Mp96Q10vUIsbsl3b68RRmTxGaeYRe7PlmL8z99Arh3mYq6iypF7u6HpxQmW7du+NwcKmRf2ZrlJcv2EZuivRMHhnM7El0xiAI5lORLi2SYtJ6ammyB+aX4idbvYvJEm0hhkmSxTK3OmKPkPe9uCBESM5wz5e+JHHH+Oo6ujyyuGYLUVvcRQIloeGtQMC5RS1zgBhx3cn4Jwpefdt6SoiIP4qzMJDaM/138ayixTuHrzJ1M/zdM8yRGn6vdxa6gG4xsKd2tjIx6fK6trVq6VFYbEuPQjXgX6MP63Bb/0H0ScnSzCW+6lsCUPanrq8OUsTEKc6gMKgd14CZNXqPp5tjRd+EfafaTyxZeY/USTPNcDeKEgKfyWJleRa7X4jA=
  matrix:
  - SUBDAG=0
matrix:
  fast_finish: true
