language: generic
sudo: required
services:
- docker
before_install:
- set -e
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp
    rm -rf /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
  fi
install: scripts/travis-setup.sh
jobs:
  include:
  - stage: Linux+macOS
    if: "(type = push) AND ((branch IN (master, bulk)) OR (fork = true))"
    os: linux
    script: scripts/travis-run.sh
  - os: osx
    if: "(type = push) AND ((branch IN (master, bulk)) OR (fork = true))"
    script: scripts/travis-run.sh
  - stage: Linux
    if: type = pull_request
    os: linux
    script: scripts/travis-run.sh
env:
  global:
  - SUBDAGS=1
  - BIOCONDA_UTILS_TAG=master
  - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
  - BIOCONDA_UTILS_LINT_ARGS=
  - MINICONDA_VER="4.3.21"
  - ANACONDA_USER='nyuad-cgsb'
  - GITHUB_USER='nyuad-cgsb'
  - MY_TRAVIS_REPO_SLUG='biosails/bioconda-recipes'
  - secure: Kzf6ESymKkb3dj1ZVHy3A9QpA6fSjwM3YVqJy9589lKs1LISxaUU+/lGWIibefMhKWkFg+H6g9Jpfm26aFeZ6qid5FR5Bz3v88+RpDW1fGGvKSbiulsymskoKSx4r7Eh8fMGeMTWYtpE1UT20zq4+oefGj1+xghlNQjfM9fbo9e5OUR3nA6fWI7gRXPOaz5kNJbinL674Ob/6iQUboe2EChcarYaMFtScpoMwlmXCRE9SXKFVpZacKPADZzwLkGCLIIvS4XggcoPekDpnwjst2GFa8+rY4IPtznzwfWovNIA+NkKJKVhyejppq8ojSUrbmaF8Evf0r17hOpLgxT5VuzSUZ39q4R0Ad6JlWMWMZDc+cqGulxcK0f+8bwqjozko1NL9NWnZ4TpVxsGYpyl3Q0DutQ818W2t6Ijm7iF42EE5Ry87ukuQe099OIethvkhKHhgUhL/ws+4mQc03JNvVB+gxLrgNLhtTyLdU9LuxXl6mMaY5zvK0AXZ+WR6QC/mL9tEGuB0YCjnRj4C/rHiX8b/C8ZWMIJIGCPOWmOtDFCXzBoy/UdAMsHFRWKWmMFDgBbMy1RrVmhIcvLQgHJC9zd9TAnrDm96VeDwlsVyjReADwa1/UDtpuAXPyjE+d3DXQCqL6/JnC+O79hFsfQ1UXC1RIAJRjXRN7DZmdyZbE=
  - secure: GLhQJG6dDtwe/3Kgxspl9hxiaECJvjLE8CS4Ooi3XWFhB7/pPhfWDvNfwyqpG/O6frrYuelLLwgyrlBpCfJolWSmHMNpN6OOES50AIm0aT8jgUZ0a0RDlpYfQgHzFEdICZKc5a9mXSMIMQADvjQGk4giKMAyF0msVjIDPoCXgXLDcAHjp1C45rLQrmFd84yRNZHO3EaN8GtNW7iqf9neuCulLVaZqL4ByXsg5jEGfNSd0uF5fmxWwQYKSh0/8XczOcontJ18HKnw51H5qWJCmWu4Qz4lXhmdC1Wbb8uqivo5B/hjculPpFXLKVad+Gug2lf7WqNyfgsqJO4KL3R+MThsXKKMD7EoNEZu4wjw0wprvvjk4PwmgvuB3IQdI6XdKwQSkL8BTmKtvWlHMDWLGcg1iWneel0kRiuq2+yT4hZdudSbd9eJnrtYovrTqVxiVY0vXmX6hyRkrpjBDCyC+KxBBx262QrBBsFn/6Ftm8V5UBGW3IOGaP8wzxcQPYj8+AHQ+BsyDucCFtEXyuu9nNUPtbMV96Ny/eL5KmwTGxeDsdGnonoPGfwR6JvLgH1KWEUhJ4F0y/AMUxYJR8enFG6Wkij9URH0sr8oF5LtnhuSw0u+aX4oP0pAw5gbWI7TWEvI9+XMh1XipgwqAF8qrSiUG3kwaUOGGFYCDfp7ZpA=
  matrix:
  - SUBDAG=0
matrix:
  fast_finish: true
