language: generic
sudo: required
services:
- docker
before_install:
- set -e
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp
    rm -rf /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
  fi
install: scripts/travis-setup.sh
jobs:
  include:
  - stage: Linux+macOS
    if: "(type = push) AND ((branch IN (master, bulk)) OR (fork = true))"
    os: linux
    script: scripts/travis-run.sh
  - stage: Linux
    if: type = pull_request
    os: linux
    script: scripts/travis-run.sh
env:
  global:
  - SUBDAGS=1
  - BIOCONDA_UTILS_TAG=master
  - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
  - BIOCONDA_UTILS_LINT_ARGS=
  - MINICONDA_VER="4.3.21"
  - ANACONDA_USER='nyuad-cgsb'
  - GITHUB_USER='nyuad-cgsb'
  - MY_TRAVIS_REPO_SLUG='biosails/bioconda-recipes'
  - CONTAINER_NAMESPACE='nyuad-cgsb'
  - secure: MrQXrgcsToB1dNSJdbjz6FiRFw2/IKQPaYhC/Wi2zWspk2RCTCy9yDttPXzkCNl+bd5Cf7ltYJBx0FDYT4QceiMMFfMMscrKsBmuUzV7sVPkFODNVgwodXHw4Vrifef3RKdIb6/kGtoaNHi2Gce7fg843yqwheqn9keNgzTC8V+PU4BqRt5ZutVuobea43/sawofNiljIzHSHEfbK/gPaPXGK6EH4yVYu5n6HEfR5LzM8pc4rPSYLWKaSq3xzELdtkitYt+oISataElNcaTWqBWi1jFLd7aBwmwJHOM1ALbwKOw5+HC99LNP5PppCSJu6JWy/1mzZROKWDLfCBF2FlrCW5gR3X7yVBTgMhs6kAJZitKEM0ttvJzWW3ZTIzyvjJCRxFe9L3xHTvWMvOQHpr/HW59klsa25yW9tuWvzykc7aaj10G0CZm4LH76tQS6mwhnQdwbVXXnu6WwZTzbWU2JTCtaUVWtxVIriulwcyL7SeeEOHmg7P1coqaVlm0+tX0+z6uIAEBVXhPf4pJZfgvCM9slxX4Zuz5qQ8i9s93dEgPA2s4QM+6OwE4/S4D3zMfXiJ8dSeWaGu+/8gylmcyiyg60g4+hrm+d1+wJi+NMaVG6/B/eW5JRBVawK4fg0EK3bxiIhxwXrrOQ3QKpctsnag+dlqHoUoDpx0LsAtE=
  - secure: QNP7i9tbzdAhwknyKvO9tY5vfNYf2CG1sKDPHpdhXQzYvVJpkTEP8F8G/57zGeLyxo+3i+CKKSH2NSr2g3IDfxD62kOGswg2BJVxFt+UNgowCIWVjR8Gw7F66NhILNM3Z7jmHC2cTtcHwreQHHYIF1wIkj/nmwE7y4ivxOz2N5V2u06zdcNuW6aWo8w7gVPmSmEK7sNstD7xRnhmTeo+0d+0W4c5D7NSR2TEKmr88nUveszXHeNLFHrkLHSvllzNkuJ2pL9JfHNAvER4/PwwkhNvqdtNuhTUxO1Zl801ClmxaUN8Nd6aEMPx6uLqaSDLHvoXA3wWUD5LDHOv1NQuSvnyuQUnSX7iJPmBENmth7qxepzpJSS7k2iUCLJt9McZuTCsoqlt5KPCR5l4Q2yVw/uhlSmpK1apKyq8oOPuWakanB2+ejj9svnf+2NhRKcmVGnk8lvkKDACK5pjwoacL5pItmjlLRl3qWmKMtBGG+xY7E1uiGA90zRP59H5xE/BPhZ1yz7hXtY3N7jjIkj/oSDwMc2Pe3QiHqXrtlLwFSUECbRuJOTQ4WjHFDSwZca1StCHYgr16JEB7NH5VrAeU0S65FGdKnn0eQn9vIDgv8Up9JK3XfOLw2DZDTWXKqwNjYOr8EAksSwMHC8hJZogUnpBUJRTNRUq3/NmRcSQYfU=
  - secure: WHcaTU0EUYYC0Wo5TCpRLBRdhQqnJ+96Pz8jIv5VUUmM270UEoyYODBmAQ62n7DaYoOaL5fpm72hbv6s7dGF5LagRhVQiXt5LmXTOZaniaId47biKUk0zFPcFzdoh5hgoe1Bd/cynAKvUy9h8U8U2kEh0L4iOd4lB04pQHrPou9ttDuyz+PLKGN9Hy9+fSRV7aKGMKPGbbgr1DNya8YN7NHvNKq0wNK4aE29RTivCBp4hzVHA9jL3XuSDooTJ/e90SmBubkzZhwCpRxGKpX0S8SfLPLb4STVIuGMxxss4YDglfXNUFgQyA2F9ImYERQZMgMKOGq9SUCFTYd1+VQQRe3EPuwlC2Tw+N2gT82vgS2tstTy8iITRFIp/EBOn/5/Aac2EQe12TniC/a6wvOHzC+MPysRLIZTsz6qkzUOoaaNv8wveHEmwre1VyUwS8A23o/yMYrs4HggOtrH2rmheBzNlXlDJaL//7kEc1twbweQnrnNYhwx4MM37uUtVIjn0OZBNAQtfXwgS98+RqbQiOMZB4tnlDN4wQZxXqdFg6rI2A3DXOevwgHdDrEB6HA1rCFhzNpSU/OFkf4Uz35I1jw7nP2Om49yiB8ZWj9GWO5OMd/Xd8HwuaE2vFp7o4moyMLr8NM1t+ZjWq/2vumEd2W1ltLKCWV0/Cfy//t+nGw=
  - secure: RKhfHPPo9LxMC41gZshBAoilvnTpz9ftM+3SSjZBOGsxa4DXr+FYOCCNE+0doUiV3mfo2zR7K40C3nvskmwuLa+qn690++ZfRTittyktbGXldAlMf8iTcP0Bt6V6HKBMvB+MG6BVnEsgrnIGMYdqoohbUEoXwpVJn/sdFvcpFAEKf8G3t0m5LRjVipc4plsFgGAxbKmjttoDT6SJAelNeFS9ugfS3eA2GxJF+86LsYY04J3YkLDzM5Ie4IVCEn05zDvjV2lYk9pJ2Ij8nddFAhFDWhWpxAXXgh7EgtFLEt25Ocgly1gvnnJaZGyyKIk9gybld4xzmjsPEjkARX56KnMzFYDvv4HMrTwF1yrsemCFcEdPSzdXh+2FIveY4M/A/G82VKvfhWIqehxmn85HIJqKLPzR0aTECtq/QsZPFTVWvEBdRzy5MVdJ7xDT0CEo2M+Vn8/M4Q4sLrW6QvPJU/8Vbqvv/Ay/iZgHckAr2RuhCSv/JVVrRcep1sOD8apNKCh98u2FqKKrZdCjBwntc5IHXFvkgqsgjbehV+6h3sLwSZ7X5LPm+8ZQ4HEYIdkWZtOrBghqa5/GNT0fZsHtQ34TI8XWFb/UmJU0uUpD6rN1sxxUrA8ZydHpCx0S7tJGlvlsuVfBEV+kJfkhHITZBzL8JwWyWt1uhTWlodGc2do=
  matrix:
  - SUBDAG=0
matrix:
  fast_finish: true
