{% set name = "gencore_test" %}
{% set version = "1.0" %}


package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: True # [osx]

requirements:
  run:
    - perl

test:
  commands:
    - echo 'hello' 


about:
  home: 'https://cgsb.abudhabi.nyu.edu/'
  license: BSD
  summary: 'Gencore Variant Detection'
